/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lodge_studio.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-3.25, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3.geometry}
          material={nodes.Fillet3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_2.geometry}
          material={nodes.Fillet3_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_3.geometry}
          material={nodes.Fillet3_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_4.geometry}
          material={nodes.Fillet3_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_4"].geometry}
          material={nodes["Cut-Extrude2_4"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_5"].geometry}
          material={nodes["Cut-Extrude2_5"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_6"].geometry}
          material={nodes["Cut-Extrude2_6"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_7"].geometry}
          material={nodes["Cut-Extrude2_7"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_103.geometry}
          material={nodes.Imported1_103.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_105.geometry}
          material={nodes.Imported1_105.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_107.geometry}
          material={nodes.Imported1_107.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_93.geometry}
          material={nodes.Imported1_93.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1.geometry}
          material={nodes.Object_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_6"].geometry}
          material={nodes["Boss-Extrude1_6"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_5.geometry}
          material={nodes.Fillet1_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude1"].geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Bed Dots"]}
        />
      </group>
      <group
        position={[-3.25, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["????????_??????2"].geometry}
          material={nodes["????????_??????2"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["??????????7"].geometry}
          material={nodes["??????????7"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1"].geometry}
          material={nodes["Boss-Extrude1"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude17"].geometry}
          material={nodes["Boss-Extrude17"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_4"].geometry}
          material={nodes["Boss-Extrude1_4"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_5"].geometry}
          material={nodes["Boss-Extrude1_5"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_7"].geometry}
          material={nodes["Boss-Extrude1_7"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer1_8.geometry}
          material={nodes.Chamfer1_8.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer2.geometry}
          material={nodes.Chamfer2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude27"].geometry}
          material={nodes["Cut-Extrude27"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude3_2"].geometry}
          material={nodes["Cut-Extrude3_2"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude4"].geometry}
          material={nodes["Cut-Extrude4"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude7_2"].geometry}
          material={nodes["Cut-Extrude7_2"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_2.geometry}
          material={nodes.Fillet1_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_3.geometry}
          material={nodes.Fillet1_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_4.geometry}
          material={nodes.Fillet1_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_6.geometry}
          material={nodes.Fillet1_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet2.geometry}
          material={nodes.Fillet2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet4.geometry}
          material={nodes.Fillet4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet4_2.geometry}
          material={nodes.Fillet4_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_122.geometry}
          material={nodes.Imported1_122.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_123.geometry}
          material={nodes.Imported1_123.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_28.geometry}
          material={nodes.Imported1_28.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_31.geometry}
          material={nodes.Imported1_31.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_70.geometry}
          material={nodes.Imported1_70.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step3.geometry}
          material={nodes.Marquardt_19011103step3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step_2.geometry}
          material={nodes.Marquardt_19011103step_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step_3.geometry}
          material={nodes.Marquardt_19011103step_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_136.geometry}
          material={nodes.Imported1_136.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_137.geometry}
          material={nodes.Imported1_137.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_14.geometry}
          material={nodes.Imported1_14.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_7.geometry}
          material={nodes.Imported1_7.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_74.geometry}
          material={nodes.Imported1_74.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_81.geometry}
          material={nodes.Imported1_81.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_83.geometry}
          material={nodes.Imported1_83.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_90.geometry}
          material={nodes.Imported1_90.material}
        />
      </group>
      <group
        position={[-3.25, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude6"].geometry}
          material={nodes["Boss-Extrude6"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer2_3.geometry}
          material={nodes.Chamfer2_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude3"].geometry}
          material={nodes["Cut-Extrude3"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude5"].geometry}
          material={nodes["Cut-Extrude5"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude7"].geometry}
          material={nodes["Cut-Extrude7"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1.geometry}
          material={nodes.Fillet1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet2_2.geometry}
          material={nodes.Fillet2_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet6_2.geometry}
          material={nodes.Fillet6_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_85.geometry}
          material={nodes.Imported1_85.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_89.geometry}
          material={nodes.Imported1_89.material}
        />
      </group>
      <group
        position={[-4.35, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3001.geometry}
          material={nodes.Fillet3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_2001.geometry}
          material={nodes.Fillet3_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_3001.geometry}
          material={nodes.Fillet3_3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet3_4001.geometry}
          material={nodes.Fillet3_4001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_4001"].geometry}
          material={nodes["Cut-Extrude2_4001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_5001"].geometry}
          material={nodes["Cut-Extrude2_5001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_6001"].geometry}
          material={nodes["Cut-Extrude2_6001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude2_7001"].geometry}
          material={nodes["Cut-Extrude2_7001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_103001.geometry}
          material={nodes.Imported1_103001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_105001.geometry}
          material={nodes.Imported1_105001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_107001.geometry}
          material={nodes.Imported1_107001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_93001.geometry}
          material={nodes.Imported1_93001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1001.geometry}
          material={nodes.Object_1001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001.geometry}
          material={nodes.Object_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_6001"].geometry}
          material={nodes["Boss-Extrude1_6001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_5001.geometry}
          material={nodes.Fillet1_5001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude1001"].geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3001.geometry}
          material={materials["Bed Dots.001"]}
        />
      </group>
      <group
        position={[-4.35, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["????????_??????2001"].geometry}
          material={nodes["????????_??????2001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["??????????7001"].geometry}
          material={nodes["??????????7001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1001"].geometry}
          material={nodes["Boss-Extrude1001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude17001"].geometry}
          material={nodes["Boss-Extrude17001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_4001"].geometry}
          material={nodes["Boss-Extrude1_4001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_5001"].geometry}
          material={nodes["Boss-Extrude1_5001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude1_7001"].geometry}
          material={nodes["Boss-Extrude1_7001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer1_8001.geometry}
          material={nodes.Chamfer1_8001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer2001.geometry}
          material={nodes.Chamfer2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude27001"].geometry}
          material={nodes["Cut-Extrude27001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude3_2001"].geometry}
          material={nodes["Cut-Extrude3_2001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude4001"].geometry}
          material={nodes["Cut-Extrude4001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude7_2001"].geometry}
          material={nodes["Cut-Extrude7_2001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_2001.geometry}
          material={nodes.Fillet1_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_3001.geometry}
          material={nodes.Fillet1_3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_4001.geometry}
          material={nodes.Fillet1_4001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_6001.geometry}
          material={nodes.Fillet1_6001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet2001.geometry}
          material={nodes.Fillet2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet4001.geometry}
          material={nodes.Fillet4001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet4_2001.geometry}
          material={nodes.Fillet4_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_122001.geometry}
          material={nodes.Imported1_122001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_123001.geometry}
          material={nodes.Imported1_123001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_28001.geometry}
          material={nodes.Imported1_28001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_31001.geometry}
          material={nodes.Imported1_31001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_70001.geometry}
          material={nodes.Imported1_70001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step3001.geometry}
          material={nodes.Marquardt_19011103step3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step_2001.geometry}
          material={nodes.Marquardt_19011103step_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Marquardt_19011103step_3001.geometry}
          material={nodes.Marquardt_19011103step_3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_136001.geometry}
          material={nodes.Imported1_136001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_137001.geometry}
          material={nodes.Imported1_137001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_14001.geometry}
          material={nodes.Imported1_14001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_7001.geometry}
          material={nodes.Imported1_7001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_74001.geometry}
          material={nodes.Imported1_74001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_81001.geometry}
          material={nodes.Imported1_81001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_83001.geometry}
          material={nodes.Imported1_83001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_90001.geometry}
          material={nodes.Imported1_90001.material}
        />
      </group>
      <group
        position={[-4.35, 1.28, 1.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Boss-Extrude6001"].geometry}
          material={nodes["Boss-Extrude6001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chamfer2_3001.geometry}
          material={nodes.Chamfer2_3001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude3001"].geometry}
          material={nodes["Cut-Extrude3001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude5001"].geometry}
          material={nodes["Cut-Extrude5001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Cut-Extrude7001"].geometry}
          material={nodes["Cut-Extrude7001"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1001.geometry}
          material={nodes.Fillet1001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet2_2001.geometry}
          material={nodes.Fillet2_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet6_2001.geometry}
          material={nodes.Fillet6_2001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_85001.geometry}
          material={nodes.Imported1_85001.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Imported1_89001.geometry}
          material={nodes.Imported1_89001.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[-2.79, 1.07, -2.16]}
        scale={[1.14, 0.48, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube000.geometry}
        material={nodes.Cube000.material}
        position={[-2.78, 1.07, -2.16]}
        scale={[1.13, 0.47, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[-2.79, 0.34, -2.16]}
        scale={[1.14, 0.6, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-2.79, 1.07, -2.16]}
        scale={[1.14, 0.48, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[-2.79, 1.07, -2.16]}
        scale={[1.14, 0.48, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-2.79, 1.07, -2.16]}
        scale={[1.14, 0.48, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={[-2.24, 1.15, -1.83]}
        rotation={[0.59, 0, 0]}
        scale={[0.07, 0, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-2.79, 0.74, -2.16]}
        scale={[1.14, 0.07, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-2.77, 0.88, -2.01]}
        scale={[0.53, 0.01, 0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-2.77, 0.83, -2.01]}
        scale={[0.41, 0.09, 0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-2.94, 1, -2.35]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.88, 0.01, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-3.13, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-3.18, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-3.25, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-3.31, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[-3.36, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-3.43, 0.83, -2.32]}
        scale={[-0.03, 0.09, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-3.84, 1.07, -2.16]}
        scale={[1.13, 0.47, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-2.79, 1.07, -2.16]}
        scale={[1.14, 0.48, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plotter_001.geometry}
        material={materials.Plotter_001}
        position={[3.82, 0, -2.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leg.geometry}
        material={nodes.leg.material}
        position={[-1.96, 0.08, -2.16]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.02, 0.75, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leg003.geometry}
        material={nodes.leg003.material}
        position={[-0.79, 0.08, -2.16]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-0.02, 0.75, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leg001.geometry}
        material={nodes.leg001.material}
        position={[-1.96, 0.21, -2.16]}
        scale={[-0.02, 0.23, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leg002.geometry}
        material={nodes.leg002.material}
        position={[-0.79, 0.21, -2.16]}
        scale={[-0.02, 0.23, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leg_body.geometry}
        material={nodes.leg_body.material}
        position={[-1.38, 0.21, -2.16]}
        scale={[1.06, 0.23, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caster.geometry}
        material={nodes.caster.material}
        position={[-1.96, 0.02, -1.79]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[-0.04, -0.02, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caster001.geometry}
        material={nodes.caster001.material}
        position={[-0.79, 0.02, -1.79]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[-0.04, -0.02, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vaster.geometry}
        material={nodes.vaster.material}
        position={[-1.96, 0.02, -2.53]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[-0.04, -0.02, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vaster001.geometry}
        material={nodes.vaster001.material}
        position={[-0.79, 0.02, -2.53]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[-0.04, -0.02, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={nodes.body.material}
        position={[-1.38, 0.72, -2.16]}
        scale={[1, 0.59, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.button.geometry}
        material={nodes.button.material}
        position={[-0.81, 1.11, -1.86]}
        rotation={[Math.PI / 2, 1.41, -Math.PI / 2]}
        scale={[0.13, 0.01, 0.09]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cap.geometry}
        material={materials.cap}
        position={[-1.38, 1.11, -2.16]}
        scale={[0.87, 0.02, 0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.front.geometry}
        material={materials.front}
        position={[-1.38, 0.72, -2.16]}
        scale={[1, 0.59, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body001.geometry}
        material={nodes.body001.material}
        position={[-1.38, 0.72, -2.16]}
        scale={[1, 0.59, 0.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table.geometry}
        material={nodes.table.material}
        position={[-1.38, 0.72, -2.19]}
        scale={[0.83, 0.03, 0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, -0.05, 0]}
        scale={[6.24, 3.82, 3.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole.geometry}
        material={nodes.pole.material}
        position={[6.08, 1.22, 3.07]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole001.geometry}
        material={nodes.pole001.material}
        position={[6.08, 1.22, -3.12]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole002.geometry}
        material={nodes.pole002.material}
        position={[3, 1.22, 3.07]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole003.geometry}
        material={nodes.pole003.material}
        position={[3, 1.22, -3.12]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole004.geometry}
        material={nodes.pole004.material}
        position={[0.04, 1.22, 3.07]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole005.geometry}
        material={nodes.pole005.material}
        position={[0.04, 1.22, -3.12]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole006.geometry}
        material={nodes.pole006.material}
        position={[-3.09, 1.22, 3.07]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole007.geometry}
        material={nodes.pole007.material}
        position={[-3.09, 1.22, -3.12]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole008.geometry}
        material={nodes.pole008.material}
        position={[-6.13, 1.22, 3.07]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pole009.geometry}
        material={nodes.pole009.material}
        position={[-6.13, 1.22, -3.12]}
        scale={[0.1, 1.5, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 1.2, -3.15]}
        scale={[7.18, 1.47, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[0, 1.2, 3.09]}
        scale={[7.18, 1.47, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-6.14, 1.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.66, 1.47, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[6.08, 1.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.66, 1.47, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[1.08, 0.32, -2.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.93, 0.29, -1.16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[-3.34, 1.25, 1.86]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[1.61, 0.29, 1.17]}
        scale={[1.61, 1.01, 1.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[3, 0.25, 2.54]}
        scale={[1.61, 1.01, 1.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-4.89, 1.35, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0.geometry}
        material={nodes.Mesh_0.material}
        position={[1.05, 0.69, -2.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_1.geometry}
        material={nodes.Mesh_1.material}
        position={[1.05, 0.69, -2.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.07}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Boss-Extrude21"].geometry}
        material={materials.Material_2}
        position={[0, 0, -0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fillet12.geometry}
        material={nodes.Fillet12.material}
        position={[0, 0, -0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Thread1.geometry}
        material={materials["Material_1.003"]}
        position={[0, 0, -0.54]}
      />
    </group>
  );
}

useGLTF.preload("/lodge_studio.glb");
