/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Edges, useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Fillet3: THREE.Mesh;
    Fillet3_2: THREE.Mesh;
    Fillet3_3: THREE.Mesh;
    Fillet3_4: THREE.Mesh;
    ["Cut-Extrude2_4"]: THREE.Mesh;
    ["Cut-Extrude2_5"]: THREE.Mesh;
    ["Cut-Extrude2_6"]: THREE.Mesh;
    ["Cut-Extrude2_7"]: THREE.Mesh;
    Imported1_103: THREE.Mesh;
    Imported1_105: THREE.Mesh;
    Imported1_107: THREE.Mesh;
    Imported1_93: THREE.Mesh;
    Object_1: THREE.Mesh;
    Object_2: THREE.Mesh;
    ["Boss-Extrude1_6"]: THREE.Mesh;
    Fillet1_5: THREE.Mesh;
    ["Cut-Extrude1"]: THREE.Mesh;
    Object_3: THREE.Mesh;
    ["????????_??????2"]: THREE.Mesh;
    ["??????????7"]: THREE.Mesh;
    ["Boss-Extrude1"]: THREE.Mesh;
    ["Boss-Extrude17"]: THREE.Mesh;
    ["Boss-Extrude1_4"]: THREE.Mesh;
    ["Boss-Extrude1_5"]: THREE.Mesh;
    ["Boss-Extrude1_7"]: THREE.Mesh;
    Chamfer1_8: THREE.Mesh;
    Chamfer2: THREE.Mesh;
    ["Cut-Extrude27"]: THREE.Mesh;
    ["Cut-Extrude3_2"]: THREE.Mesh;
    ["Cut-Extrude4"]: THREE.Mesh;
    ["Cut-Extrude7_2"]: THREE.Mesh;
    Fillet1_2: THREE.Mesh;
    Fillet1_3: THREE.Mesh;
    Fillet1_4: THREE.Mesh;
    Fillet1_6: THREE.Mesh;
    Fillet2: THREE.Mesh;
    Fillet4: THREE.Mesh;
    Fillet4_2: THREE.Mesh;
    Imported1_122: THREE.Mesh;
    Imported1_123: THREE.Mesh;
    Imported1_28: THREE.Mesh;
    Imported1_31: THREE.Mesh;
    Imported1_70: THREE.Mesh;
    Marquardt_19011103step3: THREE.Mesh;
    Marquardt_19011103step_2: THREE.Mesh;
    Marquardt_19011103step_3: THREE.Mesh;
    Imported1_136: THREE.Mesh;
    Imported1_137: THREE.Mesh;
    Imported1_14: THREE.Mesh;
    Imported1_7: THREE.Mesh;
    Imported1_74: THREE.Mesh;
    Imported1_81: THREE.Mesh;
    Imported1_83: THREE.Mesh;
    Imported1_90: THREE.Mesh;
    ["Boss-Extrude6"]: THREE.Mesh;
    Chamfer2_3: THREE.Mesh;
    ["Cut-Extrude3"]: THREE.Mesh;
    ["Cut-Extrude5"]: THREE.Mesh;
    ["Cut-Extrude7"]: THREE.Mesh;
    Fillet1: THREE.Mesh;
    Fillet2_2: THREE.Mesh;
    Fillet6_2: THREE.Mesh;
    Imported1_85: THREE.Mesh;
    Imported1_89: THREE.Mesh;
    Fillet3001: THREE.Mesh;
    Fillet3_2001: THREE.Mesh;
    Fillet3_3001: THREE.Mesh;
    Fillet3_4001: THREE.Mesh;
    ["Cut-Extrude2_4001"]: THREE.Mesh;
    ["Cut-Extrude2_5001"]: THREE.Mesh;
    ["Cut-Extrude2_6001"]: THREE.Mesh;
    ["Cut-Extrude2_7001"]: THREE.Mesh;
    Imported1_103001: THREE.Mesh;
    Imported1_105001: THREE.Mesh;
    Imported1_107001: THREE.Mesh;
    Imported1_93001: THREE.Mesh;
    Object_1001: THREE.Mesh;
    Object_2001: THREE.Mesh;
    ["Boss-Extrude1_6001"]: THREE.Mesh;
    Fillet1_5001: THREE.Mesh;
    ["Cut-Extrude1001"]: THREE.Mesh;
    Object_3001: THREE.Mesh;
    ["????????_??????2001"]: THREE.Mesh;
    ["??????????7001"]: THREE.Mesh;
    ["Boss-Extrude1001"]: THREE.Mesh;
    ["Boss-Extrude17001"]: THREE.Mesh;
    ["Boss-Extrude1_4001"]: THREE.Mesh;
    ["Boss-Extrude1_5001"]: THREE.Mesh;
    ["Boss-Extrude1_7001"]: THREE.Mesh;
    Chamfer1_8001: THREE.Mesh;
    Chamfer2001: THREE.Mesh;
    ["Cut-Extrude27001"]: THREE.Mesh;
    ["Cut-Extrude3_2001"]: THREE.Mesh;
    ["Cut-Extrude4001"]: THREE.Mesh;
    ["Cut-Extrude7_2001"]: THREE.Mesh;
    Fillet1_2001: THREE.Mesh;
    Fillet1_3001: THREE.Mesh;
    Fillet1_4001: THREE.Mesh;
    Fillet1_6001: THREE.Mesh;
    Fillet2001: THREE.Mesh;
    Fillet4001: THREE.Mesh;
    Fillet4_2001: THREE.Mesh;
    Imported1_122001: THREE.Mesh;
    Imported1_123001: THREE.Mesh;
    Imported1_28001: THREE.Mesh;
    Imported1_31001: THREE.Mesh;
    Imported1_70001: THREE.Mesh;
    Marquardt_19011103step3001: THREE.Mesh;
    Marquardt_19011103step_2001: THREE.Mesh;
    Marquardt_19011103step_3001: THREE.Mesh;
    Imported1_136001: THREE.Mesh;
    Imported1_137001: THREE.Mesh;
    Imported1_14001: THREE.Mesh;
    Imported1_7001: THREE.Mesh;
    Imported1_74001: THREE.Mesh;
    Imported1_81001: THREE.Mesh;
    Imported1_83001: THREE.Mesh;
    Imported1_90001: THREE.Mesh;
    ["Boss-Extrude6001"]: THREE.Mesh;
    Chamfer2_3001: THREE.Mesh;
    ["Cut-Extrude3001"]: THREE.Mesh;
    ["Cut-Extrude5001"]: THREE.Mesh;
    ["Cut-Extrude7001"]: THREE.Mesh;
    Fillet1001: THREE.Mesh;
    Fillet2_2001: THREE.Mesh;
    Fillet6_2001: THREE.Mesh;
    Imported1_85001: THREE.Mesh;
    Imported1_89001: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube000: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube014: THREE.Mesh;
    Plotter_001: THREE.Mesh;
    leg: THREE.Mesh;
    leg003: THREE.Mesh;
    leg001: THREE.Mesh;
    leg002: THREE.Mesh;
    leg_body: THREE.Mesh;
    caster: THREE.Mesh;
    caster001: THREE.Mesh;
    vaster: THREE.Mesh;
    vaster001: THREE.Mesh;
    body: THREE.Mesh;
    button: THREE.Mesh;
    cap: THREE.Mesh;
    front: THREE.Mesh;
    body001: THREE.Mesh;
    table: THREE.Mesh;
    Plane: THREE.Mesh;
    pole: THREE.Mesh;
    pole001: THREE.Mesh;
    pole002: THREE.Mesh;
    pole003: THREE.Mesh;
    pole004: THREE.Mesh;
    pole005: THREE.Mesh;
    pole006: THREE.Mesh;
    pole007: THREE.Mesh;
    pole008: THREE.Mesh;
    pole009: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cube022: THREE.Mesh;
    Mesh_0: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    ["Boss-Extrude21"]: THREE.Mesh;
    Fillet12: THREE.Mesh;
    Thread1: THREE.Mesh;
  };
  materials: {
    ["Black Plastic"]: THREE.MeshStandardMaterial;
    ["Satin Steel"]: THREE.MeshStandardMaterial;
    ["Black Paint"]: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    ["Bed Dots"]: THREE.MeshStandardMaterial;
    ["Black Plastic.001"]: THREE.MeshStandardMaterial;
    ["Satin Steel.001"]: THREE.MeshStandardMaterial;
    ["Black Paint.001"]: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshStandardMaterial;
    ["Bed Dots.001"]: THREE.MeshStandardMaterial;
    leg: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    sidegray: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Plotter_001: THREE.MeshStandardMaterial;
    cap: THREE.MeshStandardMaterial;
    front: THREE.MeshStandardMaterial;
    wood: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    Material_2: THREE.MeshStandardMaterial;
    ["Material_1.003"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "models//lodge.glb"
  ) as unknown as GLTFResult;
  useFrame((state) => {
    const t = state.clock.getElapsedTime();

    group.current?.rotation.set(
      0.1 + Math.cos(t / 4.5) / 10,
      Math.sin(t / 4) / 4,
      0.3 - (1 + Math.sin(t / 4)) / 8
    );
    group.current!.position.y = (1 + Math.sin(t * 2)) / 10;
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-3.3, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes.Fillet3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_4.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_4"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_5"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_6"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_7"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_103.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_105.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_107.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_93.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_1.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_6"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_5.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude1"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_3.geometry} />
      </group>
      <group position={[-3.3, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes["????????_??????2"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["??????????7"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude17"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_4"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_5"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_7"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer1_8.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude27"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude3_2"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude4"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude7_2"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_4.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_6.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet4.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet4_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_122.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_123.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_28.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_31.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_70.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step_3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_136.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_137.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_14.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_7.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_74.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_81.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_83.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_90.geometry} />
      </group>
      <group position={[-3.3, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes["Boss-Extrude6"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer2_3.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude3"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude5"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude7"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet2_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet6_2.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_85.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_89.geometry} />
      </group>
      <group position={[-4.4, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes.Fillet3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet3_4001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_4001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_5001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_6001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude2_7001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_103001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_105001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_107001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_93001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_1001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_6001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_5001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude1001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Object_3001.geometry} />
      </group>
      <group position={[-4.4, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes["????????_??????2001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["??????????7001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude17001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_4001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_5001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Boss-Extrude1_7001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer1_8001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude27001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude3_2001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude4001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude7_2001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_4001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1_6001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet4001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet4_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_122001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_123001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_28001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_31001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_70001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Marquardt_19011103step_3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_136001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_137001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_14001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_7001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_74001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_81001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_83001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_90001.geometry} />
      </group>
      <group position={[-4.4, 1.3, 2]} rotation={[0, Math.PI / 2, 0]} scale={0}>
        <mesh geometry={nodes["Boss-Extrude6001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Chamfer2_3001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude3001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude5001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes["Cut-Extrude7001"].geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet1001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet2_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Fillet6_2001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_85001.geometry}>
          <meshStandardMaterial transparent />
          <Edges />
        </mesh>
        <mesh geometry={nodes.Imported1_89001.geometry} />
      </group>
      <mesh
        geometry={nodes.Cube015.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube000.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube016.geometry}
        position={[-2.8, 0.3, -2.2]}
        scale={[1.1, 0.6, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube017.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube002.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cylinder.geometry}
        position={[-2.2, 1.1, -1.8]}
        rotation={[0.6, 0, 0]}
        scale={[0.1, 0, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube003.geometry}
        position={[-2.8, 0.7, -2.2]}
        scale={[1.1, 0.1, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube004.geometry}
        position={[-2.8, 0.9, -2]}
        scale={[0.5, 0, 0.4]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        position={[-2.8, 0.8, -2]}
        scale={[0.4, 0.1, 0.3]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube006.geometry}
        position={[-2.9, 1, -2.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.9, 0, 0.4]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        position={[-3.1, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube008.geometry}
        position={[-3.2, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube009.geometry}
        position={[-3.2, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube010.geometry}
        position={[-3.3, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube011.geometry}
        position={[-3.4, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube012.geometry}
        position={[-3.4, 0.8, -2.3]}
        scale={[0, 0.1, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube013.geometry}
        position={[-3.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube014.geometry}
        position={[-2.8, 1.1, -2.2]}
        scale={[1.1, 0.5, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Plotter_001.geometry}
        position={[3.8, 0, -2.1]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.leg.geometry}
        position={[-2, 0.1, -2.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0, 0.8, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.leg003.geometry}
        position={[-0.8, 0.1, -2.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0, 0.8, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.leg001.geometry}
        position={[-2, 0.2, -2.2]}
        scale={[0, 0.2, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.leg002.geometry}
        position={[-0.8, 0.2, -2.2]}
        scale={[0, 0.2, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.leg_body.geometry}
        position={[-1.4, 0.2, -2.2]}
        scale={[1.1, 0.2, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.caster.geometry}
        position={[-2, 0, -1.8]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, 0, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.caster001.geometry}
        position={[-0.8, 0, -1.8]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, 0, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.vaster.geometry}
        position={[-2, 0, -2.5]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, 0, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.vaster001.geometry}
        position={[-0.8, 0, -2.5]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0, 0, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.body.geometry}
        position={[-1.4, 0.7, -2.2]}
        scale={[1, 0.6, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.button.geometry}
        position={[-0.8, 1.1, -1.9]}
        rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}
        scale={[0.1, 0, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.cap.geometry}
        position={[-1.4, 1.1, -2.2]}
        scale={[0.9, 0, 0.8]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.front.geometry}
        position={[-1.4, 0.7, -2.2]}
        scale={[1, 0.6, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.body001.geometry}
        position={[-1.4, 0.7, -2.2]}
        scale={[1, 0.6, 0.7]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.table.geometry}
        position={[-1.4, 0.7, -2.2]}
        scale={[0.8, 0, 0.6]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Plane.geometry}
        position={[0, -0.1, 0]}
        scale={[6.2, 3.8, 3.2]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole.geometry}
        position={[6.1, 1.2, 3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole001.geometry}
        position={[6.1, 1.2, -3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole002.geometry}
        position={[3, 1.2, 3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole003.geometry}
        position={[3, 1.2, -3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole004.geometry}
        position={[0, 1.2, 3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole005.geometry}
        position={[0, 1.2, -3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole006.geometry}
        position={[-3.1, 1.2, 3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole007.geometry}
        position={[-3.1, 1.2, -3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole008.geometry}
        position={[-6.1, 1.2, 3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.pole009.geometry}
        position={[-6.1, 1.2, -3.1]}
        scale={[0.1, 1.5, 0.1]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[0, 1.2, -3.2]}
        scale={[7.2, 1.5, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube018.geometry}
        position={[0, 1.2, 3.1]}
        scale={[7.2, 1.5, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube019.geometry}
        position={[-6.1, 1.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.7, 1.5, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube020.geometry}
        position={[6.1, 1.2, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.7, 1.5, 0]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Cube021.geometry} position={[1.1, 0.3, -2]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Cylinder001.geometry} position={[1.9, 0.3, -1.2]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Cube023.geometry} position={[-3.3, 1.3, 1.9]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cube024.geometry}
        position={[1.6, 0.3, 1.2]}
        scale={[1.6, 1, 1.6]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Cylinder002.geometry}
        position={[3, 0.3, 2.5]}
        scale={[1.6, 1, 1.6]}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Cube022.geometry} position={[-4.9, 1.4, -0.5]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        position={[1.1, 0.7, -2.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh
        geometry={nodes.Mesh_1.geometry}
        position={[1.1, 0.7, -2.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes["Boss-Extrude21"].geometry} position={[0, 0, -0.5]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Fillet12.geometry} position={[0, 0, -0.5]}>
        <meshStandardMaterial transparent />
        <Edges />
      </mesh>
      <mesh geometry={nodes.Thread1.geometry} position={[0, 0, -0.5]} />
    </group>
  );
}

useGLTF.preload("/models/lodge_studio.glb");
